name: rust

on:
  push:
    branches-ignore: [ 'rsgx**' ]
    paths: ["benches", "examples", "src", "tests"]
  pull_request:
    # simply use 'branches' with ['!rsgx**'] isn't ok due to missing positive matches
    branches-ignore: [ 'rsgx**' ]
    paths: ["benches", "examples", "src", "tests"]

jobs:
  test:

    runs-on: ubuntu-18.04
    container: rust:1.42.0

    steps:
    - uses: actions/checkout@v2
    - name: Rust toolchains
      run: |
        rustc --version &&
        rustup --version &&
        cargo --version
      shell: bash
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Run tests
      run: cargo test --verbose
      shell: bash
